### ISSUE TITLE
Adding more info to the readme file and migrating to CC

### ISSUE THREAD

**Issue by gndaskalova** [ericazaja/ANOVA#1]
Hi @ericazaja 

Great work on updating your tutorial, exciting to see the progress! To continue ahead with publishing your tutorial on the CC website, I have made a repository on the CC account for the data and files associated with your tutorial. https://github.com/ourcodingclub/CC-anova Could you please copy over your content from this repository to the one on the CC organisation and then also update the link in your tutorial markdown file (so that the data are downloaded from the CC account)? You had a lovely comprehensive readme file in the repo for your tutorial and think it would be useful to copy some of the content about the image licenses and data into the readme for this repository.

Looks great! More from me soon but excellent progress! I gave you write access to the repo I made for you so hopefully you are able to upload files, but let me know if not!

Have a good day,
Gergana

**Comment by ericazaja** [comment]
Hello @gndaskalova ! Hope your travels are going smoothly. Thanks for taking the time to do all that!

I can confirm I have full access to the Coding Club organisation repo and I've now migrated the data there (https://github.com/ourcodingclub/CC-anova). I have changed the link in my tutorial markdown as well. I also added a more informative `README.md` as you suggested.

I look forward from hearing from you!
Best
Erica

**Comment by gndaskalova** [comment]
Looks great @ericazaja ! I changed your license for the tutorial just cause we use a creative commons license not the MIT one. The only other thing I spotted is here "Data created by me" - could you add what you mean here? Did you collect the data, or did you generate random numbers?

Thank you,
Gergana

**Comment by ericazaja** [comment]
> Looks great @ericazaja ! I changed your license for the tutorial just cause we use a creative commons license not the MIT one. The only other thing I spotted is here "Data created by me" - could you add what you mean here? Did you collect the data, or did you generate random numbers?
> 
> Thank you,
> Gergana

@gndaskalova "Data created by me", as in a wrote those numbers specifically to make sure I'd get good graphs and so that the ANOVA would run smoothly. I know, I basically p-hacked but I did it for teaching purposes! How can I phrase this in the `README.md`? Something like **dummy data generated by Erica Zaja**. Could this work? 
Erica

**Comment by gndaskalova** [comment]
That sounds good @ericazaja !
